const { tebexSecret, couponperms } = require('../config').tebex;
const { default: axios } = require('axios');
const moment = require('moment');
const { SlashCommandBuilder } = require('@discordjs/builders');

module.exports = {
    data: new SlashCommandBuilder()
        .setName('createcoupon')
        .setDescription('Create a new coupon')
        .addStringOption(option =>
            option.setName('type')
                .setDescription('Value or Percentage')
                .setRequired(true)
                .addChoices(
                    { name: 'Value', value: 'value' },
                    { name: 'Percentage', value: 'Percentage' }
                ))
        .addIntegerOption((option) => option.setName('amount').setDescription('Value / percent of coupon').setRequired(true))
        .addIntegerOption((option) => option.setName('uses').setDescription('Limit of uses, enter 0 for unlimited').setRequired(true)),
    async execute(interaction) {
        function checkUser(id) {
            let a = false;
            const user = interaction.guild.members.cache.get(id);
            const all = couponperms.split(',')
            all.forEach(curr => {
                if(user.roles.cache.find(r => r.id === curr) || !curr) {
                    a = true;
                }
            })
            return a;
        }

        if(checkUser(interaction.user.id) !== true) return interaction.reply({ content: 'You do not have permission to run this command!', ephemeral: true })

        function createCode(len) {
            const chars = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZFabcdefghijklmnopqrstuvwxyz-'
            var result = '';
            for (let i = len; i > 0; --i) {
                result += chars[Math.floor(Math.random() * chars.length)];
            }
            return result;
        }

        const code = createCode(10)

        await axios({
            method: 'post',
            url: 'https://plugin.tebex.io/coupons',
            headers: { 'X-Tebex-Secret': tebexSecret },
            data: {
                code: code,
                effective_on: "cart",
                packages: [],
                discount_type: interaction.options.get('type').value,
                discount_amount: interaction.options.get('amount').value,
                discount_percentage: interaction.options.get('amount').value,
                redeem_unlimited: interaction.options.get('uses').value === 0,
                expire_never: true,
                minimum: 0,
                expire_limit: interaction.options.get('uses').value,
                discount_application_method: 0,
                note: 'Auto-generated By Bot',
                basket_type: 'both',
                start_date: moment().format('YYYY-MM-DD'),
            }
        })

        interaction.reply({content: `Your coupon code is \`${code}\``, ephemeral: true})

        
    },
};