const { tebexSecret, couponperms } = require('../config').tebex;
const { default: axios } = require('axios');
const moment = require('moment');
const { SlashCommandBuilder } = require('@discordjs/builders');

module.exports = {
    perms: [],
    data: new SlashCommandBuilder()
        .setName('createcoupon')
        .setDescription('Create a new coupon')
        .addStringOption(option =>
            option.setName('type')
                .setDescription('Value or Percentage')
                .setRequired(true)
                .addChoices(
                    { name: 'Value', value: 'value' },
                    { name: 'Percentage', value: 'percentage' }
                ))
        .addIntegerOption((option) => option.setName('amount').setDescription('Value / percent of coupon').setRequired(true))
        .addIntegerOption((option) => option.setName('uses').setDescription('Limit of uses, enter 0 for unlimited').setRequired(true)),
    async execute(interaction) {
        function createCode(len) {
            const chars = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZFabcdefghijklmnopqrstuvwxyz-'
            var result = '';
            for (let i = len; i > 0; --i) {
                result += chars[Math.floor(Math.random() * chars.length)];
            }
            return result;
        }

        const code = createCode(10)

        await axios({
            method: 'post',
            url: 'https://plugin.tebex.io/coupons',
            headers: { 'X-Tebex-Secret': tebexSecret },
            data: {
                code: code,
                effective_on: "cart",
                packages: [],
                discount_type: interaction.options.get('type').value,
                discount_amount: interaction.options.get('amount').value,
                discount_percentage: interaction.options.get('amount').value,
                redeem_unlimited: interaction.options.get('uses').value === 0,
                expire_never: true,
                minimum: 0,
                expire_limit: interaction.options.get('uses').value,
                discount_application_method: 0,
                note: 'Auto-generated By Bot',
                basket_type: 'both',
                start_date: '2020-01-01',
            }
        })

        interaction.reply({content: `Your coupon code is \`${code}\``, ephemeral: true})

        
    },
};